name: nos
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'  # 🔥 Adicionando restrição mínima do SDK do Dart

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  # 🔥 Suporte a múltiplas localizações

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  table_calendar: ^3.1.3
  image_picker: ^1.0.7  # 🔥 Permite selecionar imagens da galeria
  path_provider: ^2.1.1  # 🔥 Permite salvar arquivos no armazenamento interno
  flutter_launcher_icons: ^0.14.3  # 🔥 Configuração do ícone do app

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/2_icone.png"  # 🔥 Caminho atualizado para o novo ícone
  adaptive_icon_background: "#FFFFFF"  # 🔥 Cor de fundo (para Android)
  adaptive_icon_foreground: "assets/2_icone.png"